chcp 65001
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_left.png" "ア_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_right.png" "ア_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_left.png" "カ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_right.png" "カ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_left.png" "サ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_right.png" "サ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_left.png" "タ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_right.png" "タ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_left.png" "ナ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_right.png" "ナ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_left.png" "ハ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_right.png" "ハ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_left.png" "マ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_right.png" "マ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_left.png" "ヤ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_right.png" "ヤ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_left.png" "ラ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_right.png" "ラ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_left.png" "ワ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_right.png" "ワ_right.svg"
pause
exit